"""Initial migration

Revision ID: bb6d117dddc5
Revises: 
Create Date: 2026-06-12 18:09:56.277141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb6d117dddc5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('draft_estimation_sessions', 'uploaded_page_paths',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index(op.f('idx_estimation_sessions_user'), table_name='estimation_sessions')
    op.create_index(op.f('ix_estimation_sessions_user_id'), 'estimation_sessions', ['user_id'], unique=False)
    op.alter_column('in_platform_notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_in_platform_notifications_id'), 'in_platform_notifications', ['id'], unique=False)
    op.drop_index(op.f('idx_sessions_token'), table_name='sessions')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sessions_token'), 'sessions', ['token'], unique=False)
    op.drop_index(op.f('ix_in_platform_notifications_id'), table_name='in_platform_notifications')
    op.alter_column('in_platform_notifications', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_estimation_sessions_user_id'), table_name='estimation_sessions')
    op.create_index(op.f('idx_estimation_sessions_user'), 'estimation_sessions', ['user_id'], unique=False)
    op.alter_column('draft_estimation_sessions', 'uploaded_page_paths',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    # ### end Alembic commands ###
